services:
  postgres:
    image: postgres:16
    container_name: technova_postgres
    environment:
      POSTGRES_USER: technova
      POSTGRES_PASSWORD: technova_pwd
      POSTGRES_DB: technova_attrition
    ports:
      - "5432:5432"
    volumes:
      - technova_pgdata:/var/lib/postgresql/data
      - ./data/raw:/data/raw:ro
      - ./sql:/sql:ro

volumes:
  technova_pgdata:
